In [1]:
import numpy as np

In [11]:
r = np.array(np.arange(0,36,1))

In [12]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [15]:
r = r.reshape(6,6)

In [16]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [19]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [20]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [22]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [23]:
type(lambda x: x+1) 

function

In [25]:
r[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]